- lib/response.js
- test/reply.js
> allow replying with a stream as returned by node core http client methods

- API.md
- npm-shrinkwrap.json
Documented new `index` options for directory handler
Closes #2367
> Update API.md for inert 2.1.0

- test/request.js
This fixes the occasional test issue but it may be hiding a bug.
> Closes #2414

- CHANGELOG.md
All credit to @diffsky https://gist.github.com/diffsky/73f62e1430d84c16d51b
> updated changelog closes #2406

- npm-shrinkwrap.json
> Update mime-db to 1.7.0 from 1.6.1

- API.md
reply.continue() is the correct callback to use when authentication completes successfully. The example code should reflect that.
> Update server.auth.scheme example code

- API.md
Fixes minor issues spotted in the documentation while learning to be Hapi.
> Minor grammar and spelling corrections.

- npm-shrinkwrap.json
This should help people having trouble migrating.
Related hapijs/joi#580 & #2438.
Closes #2464
> Update shrinkwrap to joi 6.0.7

- lib/connection.js
- package.json
- test/connection.js
- test/handler.js
- test/reply.js
- test/route.js
- test/transmit.js
after https://github.com/cjihrig/hapi-scope-start/pull/1 is merged this will clean up all the remaining linter warnings
> clean up lint

- lib/transmit.js
- test/transmit.js
> Retain content-length header for HEAD requests

- package.json
Has discussed in hapijs/qs#88 running lab from the package.json no need the node_moudles bin path
> Cleanup lab invoke

- lib/server.js
This PR closes issue https://github.com/hapijs/hapi/issues/2663.
> allow for proto inherit with Server ("instanceof" instead of "===")

- test/response.js
Currently fails on the etag comparison.
> Add failing test for #2628

- API.md
Docs now reflect failAction takes an optional callback parameter.
> update all failAction references to with allowed value of callback

- npm-shrinkwrap.json
> Update catbox-memory to v1.1.2

- API.md
- lib/methods.js
- test/methods.js
Adds catbox stats to server methods cache object. Closes #2763
> Add cache stats to server methods

- API.md
Tiny change to the plugin registration example. Also updated the usage of 'server.views' to match the view tutorial example.
> Updated documentation for Error response

- API.md
Per https://github.com/hapijs/hapi/commit/2f232985f163d64bb58bd37276692346b6bd502b#commitcomment-13575066
> Fix joi empty payload example in docs.

- test/route.js
- test/transmit.js
Found while working on linting updates.
> Style fixes

- package.json
* More hapi lint rules 
* Better code coverage detection
> Upgrade lab and use shuffle option

- API.md
> Fix description of server.state option ignoreErrors

- test/state.js
* Fixes https://github.com/hapijs/hapi/issues/2996
OK, doesn't really fix anything since nothing was wrong, but I reckon this is a good test anyway.
> test for strictHeader false

- API.md
Spelling fix and change a closing brace to a closing paren.
> Documentation spelling/grammar fix

- API.md
- give some details about the the 'cache' configuration and what happens with catbox
- add request.generateResponse to the API toc
> update API docs

- lib/response.js
- test/transmit.js
Please let me know if I missed something
> Fixes #3155 - Calling reply without a payload on a JSONP route throws

- lib/request.js
- npm-shrinkwrap.json
- package.json
> Bump hapijs/boom version to 4.0.0 from 3.2.2

- npm-shrinkwrap.json
> Update hapijs/shot to 3.3.2 from 3.3.1

- API.md
> Document request.connection

- API.md
Some of the changes are obviously minor but some of them are significant and I'm not certain about all of them.  I've tried to parse the docs, example code, source code and tests but there may still be errors with these suggested edits.  Please tell me if so and I'll happily update them.
> Updates to 16.1.1 API docs

- test/payload.js
From https://github.com/hapijs/discuss/issues/516
> Return 413 when payload too large.

- lib/auth.js
- lib/response.js
- lib/transmit.js
- lib/validation.js
- package.json
See https://github.com/hapijs/contrib/issues/112 for discussion and https://github.com/hapijs/contrib/pull/113
> Update lab and fix indentation

- API.md
> Document valid path parameter characters

- SPONSORS.md
Thanks again for all the great work on hapi! I couldn't imagine using anything different.
> Updating my personal sponsor to represent my app :)

- API.md
Back port from https://github.com/hapijs/hapi/commit/054f216921cf27bfd44fa2261d921185c9505caa
Fixes #3604 for v16
> fix(api.md): add strategy to request.auth docs

- API.md
Hey 👋 
Before I make any comments about this PR, I just wanted to say a huge thanks to everyone who's contributed to Hapi, I'm a huge fan of the project and don't know what I'd do without it! 🙏 
Regarding the change, I just noticed this as I was skimming through the API documentation.
If there's a need/want I'd be happy to review the rest of the documentation fully ✌️
> Fix tiny spelling mistake

- API.md
Point request object links to the correct anchor.
> Fix #request-object links

- API.md
Hello!
Updated an example in the documentation as per the hapi 17 changes.
Cheers
> fix request.log example

- API.md
As discussed here: https://github.com/hapijs/discuss/issues/651
> Update API.md - pointer to Vision for .view()

- lib/validation.js
- test/validation.js
> Respect a response status schema of true

- API.md
Edit documentation, fix grammar
> Documentation edit

- API.md
This PR is a documentation update and is in reference to https://github.com/hapijs/hapijs.com/issues/580
Before:
After:
> Updates link to Server Events in API.md

- API.md
- lib/request.js
- test/cors.js
> Revert "Ensure request.info.cors is set for special routes"

- API.md
Fix: https://github.com/hapijs/hapijs.com/issues/603
> Add rules processor first param explanation

- lib/headers.js
- test/state.js
> Set cookie autoValue only when no value received

- API.md
Issue: https://github.com/hapijs/discuss/issues/751
Just a short docs update
> Clarify flags parameter usage for server method functions

- API.md
- lib/config.js
- lib/route.js
- lib/validation.js
- test/validation.js
Closes #3832.
An alternative for https://github.com/hapijs/hapi/pull/3881.
> Add validation for cookies (alt impl)

- API.md
change `state` to `payload` in Payload processing
> change `state` to `payload` in Payload processing

- lib/response.js
- test/toolkit.js
cherrypick fix for #3884 to v17 branch.
> Handle signals in onRequest. Closes #3884

- API.md
- lib/config.js
- lib/core.js
- lib/request.js
- lib/route.js
- lib/server.js
- lib/toolkit.js
- test/payload.js
- test/request.js
- test/server.js
This will eventually replace the `response` event (removed next major). Related to feedback from #4053.
> Add new ext onPostResponse

- lib/route.js
- test/route.js
Resolves https://github.com/hapijs/hapi/issues/4122
> Removing the route timeout validation

- lib/auth.js
- lib/cors.js
- lib/headers.js
- lib/security.js
- lib/transmit.js
- test/transmit.js
This is a proper fix for the issue in #4161. Also includes a failing test.
> Use response instead of request when marshalling

- API.md
Updated function signature to keep it consistent with the documented params
> Update documented query parser argument name

- SPONSORS.md
This updates the sponsors file to reflect current sponsors.
> meta: update sponsors list

- API.md
- lib/core.js
- test/core.js
> Add closing event

- package.json
Make it match https://github.com/hapijs/hapi/issues/4386#issuecomment-1312578283
> Fix node version requirement

- lib/request.js
- test/request.js
Fixes #4395
I'm unfamiliar with Hapi's test designs; please let me know if the test needs any changes.
> Fix handling of no remoteAddress available

- lib/types/route.d.ts
Add type for https://github.com/hapijs/hapi/pull/4351 PR.
> Add type for preflight status code in cors options

- README.md
> adding colin to tsc members

- lib/types/server/ext.d.ts
- lib/types/server/server.d.ts
There is a lot of places where I need correct app state without extending hapi types and lots of custom types.
I'll try to help you with types.
> Pass ServerApplicationState to server extensions

- API.md
- package.json
- test/state.js
Related: https://github.com/hapijs/statehood/pull/88
> feat: add support for cookie partition
