hapijs/hapi

lib/methods.js
lib/response.js

Adds compatibility for promises that implement the bare A+ spec
Closes #2323

Remove catch call for promise replies

---

lib/connection.js
test/transmit.js

While I guess the payload is allowed, it is quite redundant and adds a  `content-type` header.

Remove '{}' payload from cors OPTIONS response

---

npm-shrinkwrap.json
test/security.js

Update inert to 2.1.2 which includes more detailed failure http response codes.
This means that eg. `EMFILE` errors are no longer reported as `404 Not Found ` but respond with an internal error. Also, `403 Forbidden` will now be returned instead of `404 Not Found` when the server is not allowed to access a file.
Closes #2373

inert 2.1.2

---

API.md
lib/connection.js
test/connection.js

As described in joyent/node#9066, `node` can continue to emit `request` events on closed http servers. This patch works around this by checking if the server is stopping before responding to incoming requests.

Refuse to handle incoming request after server is stopped

---

lib/connection.js
test/connection.js

This also fixes the _removes connection event listeners after it stops_ test to do what it says.

Don't respond to connections until listening is started

---

lib/validation.js
test/security.js

Validation field should also be escaped.
```json
{"statusCode":400,"error":"Bad Request","message":"&lt;script&gt;&lt;&#x2f;script&gt; is not allowed","validation":{"source":"query","keys":["<script></script>"]}}
```

Add xss protection to validation response

---

lib/plugin.js
test/route.js

this shouldn't be possible, and is very confusing for someone new to hapi.

throw when attaching route handlers without a connection

---

npm-shrinkwrap.json
test/security.js

I have reverted the 2.1.2 update which modified the null byte security test, as the new version returns a 404 again.
Closes #2398

Inert 2.1.3 update

---

API.md

Fix the minor typo in the `server.after(method, [dependencies])` docs.

Minor typo in server.after docs

---

lib/route.js
lib/schema.js
test/connection.js
test/route.js

This patch improves route method option handling in 3 ways:
1. It fixes a bug in the validation which allows a nested array (eg.  `['GET', ['POST']]`) but later crashes when creating the route.
1. It enforces the non-`HEAD` method restriction from the API docs.
1. It limits the allowed value to token characters from https://tools.ietf.org/html/rfc7230#section-3.2.6.
Finally, I have included a couple of tests for `HEAD` responses, validating the existing implementation.

Improved validation of route method label

---

lib/plugin.js
lib/schema.js
test/plugin.js

Fixes #2332.
I have a small doubt on L248 of this patch, `server` is the same as `selection` right ?

Support inline dependencies on plugins

---

lib/methods.js
test/methods.js

Fixes #2401
added to the regex to allow leading $ and _
added two tests to validate that the leading $ _ is allowed for a method name

Add regex to allow leading $ and _

---

lib/response.js
test/reply.js
test/transmit.js

Fix #2368 & #2301 by returning an explicit error for non`Readable` streams instead of throwing.
This also fixes buggy behavior introduced in #2302, where a `Writable` only stream can be accepted as long as it contains a `socket._readableState` object.

Return explicit error when trying to stream a non-Readable stream

---

lib/transmit.js
test/payload.js

This includes a new test that fails on all version of node.
I'm not entirely sure that the fix I have implemented is the best way to handle this issue but it seems to do the trick without messing up any other tests.

Fix for #2427

---

API.md
lib/validation.js
test/validation.js

Extends response schema validation to receive the same default context as input validation currently does.

pass context to response schema validation

---

API.md

correct the name of the object

---

API.md
lib/connection.js
lib/request.js
test/connection.js

Allow server.inject options parameter to specify a .artifacts object too, so that we can test handlers that use the authentication by-product artifacts too. This was done similarly to how the .credentials object is passed there.
A test was added to verify this behavior. API documentation updated.

Fix Hapi Issue #2501, pass on auth artifacts object in server.inject

---

CHANGELOG.md
Makefile

mdchangelog to 0.7 supports restricting dependents to the same github organization. This PR:
- uses the new flag
- uses the remote flag to allow folks to run mdchangelog from their forks
- has an updated changelog
Should mdchangelog be a devdependency?

#2525 update changelog and generation command

---

API.md
lib/auth.js
test/auth.js

I took the simplest approach that I could think of here. Let me know if anything should be changed.

Dynamic authentication scopes

---

API.md
lib/request.js
test/request.js

- added optional `qsParserOptions` parameter to `Request.setUrl()`
- added test illustrating use case prompting #2480
- updated `API.md` to reflect new parameter; added info about `stripTrailingSlash` as well

closes #2480: Ability to pass options to qs for payload parsing

---

lib/connection.js
test/connection.js

Added error listener to listener object. Closes #2561.

Added "error" event listener

---

API.md

A straight quote was used in place of a backtick.

Fix backtick in docs

---

API.md

Addresses typo regarding plugin dependencies. Closes #2601.

Documentation typo fix. Closes #2601.

---

API.md

Even with this change this is still confusing documentation / API in general (to me it'd be simpler if there were just `temporary()` or `permanent()`):
> `temporary(isTemporary)` - sets the status code to `302` or `307`
> `permanent(isPermanent)` - sets the status code to `301` or `308`
In reality either method can set the status to any of the 4 codes depending on its argument value and `rewritable()`.

Fix inverted boolean argument documentation.

---

npm-shrinkwrap.json

Fixes invalid ETag generation on initial 304 responses, or range requests.

Update inert to 2.1.6

---

API.md

Fix a typo in the API documentation

Correct a typo

---

test/plugin.js

Using `server.ext` option `before` as an array misbehaves, essentially ignoring the dependencies.
Root cause in topo has a pending PR: https://github.com/hapijs/topo/pull/7.  I've verified that patching topo allows all tests to pass.

Failing test for `server.ext` with complex deps.

---

npm-shrinkwrap.json

Resolves #2657 and #2671.  See failing test at #2642.

Update topo to 1.0.3

---

lib/connection.js
lib/request.js
npm-shrinkwrap.json
test/connection.js
test/plugin.js

I've made an assumption here that checking if a `request` had a `connection` property was only because Shot requests don't have one. Please tell me if this is a false assumption.

Update hapijs/shot to 1.6.0 from 1.5.3

---

lib/route.js
test/validation.js

When using [swagger](https://github.com/glennjones/hapi-swagger) for API documentation, setting `sample = 0` in response validation causes the schema not to be displayed in the documentation page.
This is because the `route.settings.response object` is set to null if sample === 0.  
Instead of doing this, skipping the validation step if sample === 0 keeps the same performance characteristics without removing any information from the route.

No longer removing response validation from route object if sample = 0

---

lib/methods.js
lib/schema.js
test/methods.js

This is designed to catch simple mistakes like this:
server.method({
name: 'myMethod',
method: function () { ... },
cache: {
expiresIn: 1000
}
});
which should really be:
server.method({
name: 'myMethod',
method: function () { ... },
options: {
cache: {
expiresIn: 1000
}
}
});

Added schema validation when creating a server method using object

---

lib/plugin.js
lib/schema.js
test/plugin.js

See #2666 
Add alias to `options` object passed to `server.register`.
The alias is passed to the `Plugin` constructor, and assigned to `this.alias`. From there, it is referenced in `expose()`. I am open to other suggestions on how to pass the **alias** to the `expose()` method. 
This option is only valid when registering one plugin at a time. If `options.alias` is specified when registering multiple plugins at once, and error is thrown.
I am currently not verifying that the alias does not overwrite an existing plugin's namespace in `server.plugins`. Is this something that is important? Since the alias is user-specified, it seems unlikely that they would unintentionally overload another existing plugin.
*Documentation updates still to come.* I wanted to iterate on this PR before working on …

add plugin alias and tests

---

API.md

This was gobbling server.inject up into a code block on the website

Properly terminate code block in API.md for server.initialize

---

lib/server.js
test/server.js

Updated the start method of server to verify that a callback was
passed. If no callback is passed, a friendly error is thrown.
Error: A callback is required when calling server.start
This is compared to the old error which required some digging
to find the cause of the problem.
TypeError: callback is not a function
Related to #2705

Updated error when calling server.start with no callback

---

API.md

I was really bummed to discover that despite the documentation, providing a custom `failAction` function is not supported in Route Prerequisites.
This removes the documentation error, which looks to be a copypasta mistake in 98a3f02cf03f1c02633ea3ba779d2878f18d217d
BTW, this would be a great feature to have, are there any plans to implement it / is anybody working on it?

Fix incorrect docs for Route Prerequisites custom failAction

---

API.md

Missing from https://github.com/hapijs/hapi/commit/69c9d737e21477c89a243802b44ac967eecbdcc#diff-88333ba11114e014e87198d04680144dR1080.

Missing tick in API docs.

---

API.md

As pointed out in #2746 there are various places in the docs that indicate a `failAction` callback can be provided.  Turns out that's not quite the case!  It can only be used with route validation options.  This PR removes it from cookie parsing, payload parsing, and response validation sections of the docs (#2741 fixed for route prerequisites).  Wouldn't mind if someone made double sure that these options can go, but as far as I can tell, the tests, schema, and codebase indicate that they can.

Fix mis-documentation of various failAction options

---

API.md

Tiny update to docs to show correct usage of `next` in `server.after` callback so that correct pieces are in place for anyone copying the example.

Add next to docs example for server.after

---

API.md

Since the Joi project moved their API docs into `/API.md` this updates the link to point to the same information as was previously pointed to.

update link to Joi options docs

---

API.md
lib/route.js
lib/schema.js
test/transmit.js

See https://scotthelme.co.uk/hsts-preloading/ for more information.
Also fixes casing issue in HSTS header: includeSubDomains - http://tools.ietf.org/html/rfc6797.

Add preload flag to HSTS header and fix casing for includeSubDomains.

---

lib/response.js
test/response.js
test/transmit.js

This is in relation hapijs/h2o2#17 .
accept-encoding value in vary header was being duplicated. This fixes the issue and adds a test case to cover the scenario.
I could have fixed it instead in [lib/response.js](https://github.com/hapijs/hapi/blob/master/lib/response.js#L129), to not add a value if it already exists in a header but I thought that was too brittle to do there.
PS: forgot to say, I will make a lts PR if this is accepted.

don't duplicate accept-encoding in vary header

---

lib/response.js
test/response.js

This works around a byte truncation flaw in node core versions > 0.10
where the high bit is stripped from headers leading to a possible header
injection.

Detects and rejects malformed response headers

---

API.md
lib/plugin.js
lib/schema.js
test/plugin.js

Added more information to the plugin results of `registrations`.

Expanded `registrations` API. Added test. Updated docs.

---

lib/cors.js
test/cors.js

Add error messages to 404's caused by cors closes #2857

---

API.md
lib/defaults.js
test/cors.js

PR request by @hueniverse in #2855 
I hope I interpreted the PR right.

Add 'Accept' to default header per #2855

---

lib/response.js
lib/transmit.js
test/transmit.js

The transmit logic incorrectly considers missing `content-length` headers as having a payload length of `0`, while it usually signals that chunked transfer encoding should be used (with any actual length).
This patch fixes this by always parsing the header value, and testing using integer comparisons instead of the current truthiness tests.
I have added 2 new tests to verify the chunked response behavior. I also fixed an existing compression test, which was actually not working as intended due to not signalling a compressible mime type.

Fix empty content-length handling for gzip and 204 responses

---

lib/cors.js
test/cors.js

During a normal request the route is looked up using the [value of `request.info.hostname`](https://github.com/hapijs/hapi/blob/master/lib/request.js#L331):
```javascript
const match = this.connection._router.route(this.method, this.path, this.info.hostname);
```
However during an OPTIONS request, it's currently being looked up via the [value of `request.headers.host`](https://github.com/hapijs/hapi/blob/master/lib/cors.js#L101):
```javascript
const route = request.connection.match(method, request.path, request.headers.host);
```
These values are different when not using port 80, therfore this can cause the route not to be found correctly when there's a vhost setting on a route as per https://github.com/hapijs/glue/issues/38 https://github.com/hapijs/hapi/issues/2930.

Lookup route during OPTIONS by using request.info.hostname. Closes #2930

---

API.md

Added missing notice that `config.security.xframe` defaults to `true`

Update API.md with xframe default

---

npm-shrinkwrap.json

This contains a fix in subtext where timeouts weren't respected on multipart payloads, fixing https://github.com/hapijs/subtext/issues/19. 
Related: https://github.com/hapijs/hapi/issues/2825 and https://github.com/hapijs/discuss/issues/171

Update hapijs/subtext to 3.0.1 from 3.0.0

---

lib/connection.js
lib/cors.js
test/connection.js

After the [recent special routes changes](https://github.com/hapijs/hapi/commit/98d34046392006540b64a799b6ca58150d08df2c#diff-259dec4414a400a6e895f16ff1d0ca3bR377), a server configured to use an authentication strategy by default for all routes...
```
const server = new Hapi.Server({ connections: { routes: { auth: "foo" } });
server.connection(...);
...
server.auth.strategy("foo", ..., ...);
```
... would fail to start and instead throw an error.
```
Unknown authentication strategy: foo in path: /{p*}
```
I also doubt the special routes are supposed to require authentication in the first place, as they didn't till the aforementioned commit.
This fixes it.
However, it might be better to just ignore authentication-related options for routes where `method === "_special"`, instead of passing …

Fails to set a global route auth config

---

lib/schema.js
test/validation.js

This might save someone some time debugging in the future. Currently we can add:
````javascript
server.route({
method: 'GET',
path: '/',
handler: function (request, reply) {
return reply('ok');
},
config: {
response: {
schema: Joi.string(),
options: {
stripUnknown: true
}
}
}
});
````
Which actually wouldn't strip any unknown keys without the `modify` key set true. With this PR if we add a route with response option `stripUnknown` set true without `modify` set to true, it will throw a validation error.

Add validation check for stripUnknown route response option

---

package.json

It conflicts with the shrink-wrapped version. npm gets confused.

Fix hapijs/shot dependency

---

API.md

The `server.method` examples with caching were missing the required `generateTimeout`. Added `generateTimeout: 100` to the examples where applicable.

server.method examples with caching were missing generateTimeout

---

lib/response.js

Hi, I've been doing some profiling to a REST API I've been working on and noticed that, for large JSON responses, a lot of time was being spent stringifying the actual responses. After some digging, I found out that the performance of the native V8 JSON.stringify degrades very quickly when the method is called with more than 1 argument (the Javascript object to stringify itself), even if the other arguments are null or undefined.
I've done some simple but yet conclusive tests with JSON.stringify and got some results to share:
* Object to stringify: [fathers.txt](https://github.com/hapijs/hapi/files/80244/fathers.txt)
* Script used:
```javascript
// Copy pasted data into variable fathers.
var fathers = ....;
// Test 1.
var startTime = Date.now();
JSON.stringify(fathers, null, null); …
```

Update JSON response stringify for better performance

---

API.md

Reference: https://github.com/hapijs/discuss/issues/239
`request.app` seems to be the place for request-specific state. This is a proposal for a more precise description.

Update API.md: added a more precise description for `request.app`

---

lib/server.js
test/server.js

I often run into issues in tests when `server.initialize()` is called multiple times. At the moment an error is thrown when it happens:
> Cannot initialize server while it is in initialized state
This PR changes the behavior, when the server is in `initialized` state, it doesn't attempt to run the initialization process again, it just calls the callback. I opened this PR to receive initial feedback, happy to improve it later.

Don't re-initialize the server

---

lib/reply.js
test/response.js

Hi, 
When calling reply().unstate(name, options) the options are sent in the 'set-cookie' response header. 
However when calling reply.unstate(name, options) - the options are not sent, therefore it is not possible to remove a cookie that has been set on a particular 'Path'.

Pass through cookie options when calling reply.unstate()

---

API.md

Just found some misplaced/mismatched backticks and asterisks in the API docs.

Fix mismatched backticks in API docs

---

API.md
lib/schema.js
lib/transmit.js
test/transmit.js

Sometimes you just don't want Cache-Control headers at all.
One example is old IE versions not loading fonts with a Cache-Control header.

Enable disabling cache-control headers

---

lib/connection.js
lib/transmit.js
test/connection.js
test/transmit.js

When a server is handling persistent connections (using http keep-alive), the `timeout` option for `server.stop()` is a bit mislabeled. If just one of the persistent connections don't make any requests within the timeout duration, the server waits for the timeout even though no requests are processing. As such, it is effectively a stop delay option.
This patch tracks the request processing state of the connections, and immediately ends idle connections on `server.stop()`. Additionally, it signals that the server is closing on active requests (by adding `connection: close` to the response), and forcibly ends the connection once the response has been submitted. This means that the `timeout` option works as expected, and the server is much more likely to stop before the timeout is reached). …

Fast server shutdown

---

API.md

Adding clarity to the docs about when dependencies are enforced and when the `srv.dependency(deps, after)` callback runs.

Clarify in API that plugin deps are enforced during initialize

---

npm-shrinkwrap.json
test/payload.js

Closes https://github.com/hapijs/hapi/issues/2825

Update hapijs/subtext to 4.0.1 from 4.0.0

---

API.md

I found this wording confusing, and noticed other people have as well (e.g. https://github.com/dwyl/hapi-auth-jwt2/issues/137 ).  I think the proposed update better reflects when `server.auth.strategy` sets a default strategy for routes.

Improve wording of auth strategy mode/default

---

lib/schema.js

fixes #3119
was not sure where to test, just add a test with arrays under test/validation.js ?

allow array as valid validate config on headers, params, query and payload

---

lib/transmit.js
test/transmit.js

The behavior of `res.writeHead()` is changed in Node@6 (and possibly node@4.4.5) so that it can throw a `RangeError` for certain statusCodes, see https://github.com/nodejs/node/pull/6291. When this throws, hapi will log an internal error without sending a response.
This PR adds a `try/catch` to catch this error and respond with a `500` to the client instead.
Additionally, it will catch thrown errors from `res.setHeader()`, eg. for an empty string header, and respond as above.

Handle thrown error from res.setHeader() and res.writeHead()

---

lib/transmit.js
test/connection.js

I noticed that a `HEAD` request for some of my routes did not send the `content-length` header, while a normal `GET` request would. I have updated the logic to properly set the header. This is done by not skipping the marshal step.
This also fixes specific cases where the `content-type` header could be different for `GET` and `HEAD` if it is set during or post marshaling.
FYI, the modified and new test both fail on current master as follows:
```
Failed tests:
141) Connection route() responds to HEAD requests for a GET route:
Expected undefined to equal specified value
at /hapijs/hapi/test/connection.js:1690:63
143) Connection route() returns 500 on HEAD requests for failed responses:
actual expected
200500
Expected 200 to equal specified value
at /hapijs/hapi/test/connection.js:1749:48 …
```

Send correct response for HEAD requests

---

lib/validation.js
test/validation.js

Set route validation bind context

---

lib/methods.js
lib/protect.js
lib/reply.js
lib/response.js
test/request.js

Fixes #3073.
It's important with promises that anything callback-style be called on next tick, otherwise any error will be caught into the promise. I might have missed places where it would happen, happy to complete the PR if you can think of any.

Delay continuations when promises may be involved

---

lib/response.js
test/reply.js

the only thing this doesn't cover from that issue is adding an `unhandledRejection` handler, which i'm still not sure how i feel about anyway

handle more types of promise rejection, for #3102

---

lib/transmit.js
test/transmit.js

Since the `content-range` header relies on an unmodified entity response, we need to leave it alone.

Ensure that 206 responses are never compressed

---

API.md

The docs on the [request object](https://github.com/hapijs/hapi/blob/db98dbb2b1bf026c5e489248ec2ea758bb47a7c3/API.md#request-object) `path` property can easily be read to mean that it corresponds to `request.url.path`, but it's really `request.url.pathname`.
The term *URL path* is pretty hazy, so if you don't like this, an alternative would be:
```diff
- the request URI's path component.
+ the request URI's path (equal to `request.url.pathname`).
```
The important thing is it should clearly communicate that `request.path` corresponds to `request.url.pathname`.
I don't know how stable the fragment links in the Node docs are (just saw a broken one, I think in some hapijs project docs), but I included the current link to `pathname`.

Correct request.path docs

---

npm-shrinkwrap.json

We cannot shrinkwrap with hapi anymore because subtext 4.2.1 requires wreck@8 but this tells it to take wreck@9, updated subtext and aligned the shrinkwrap in this PR.
Depends on https://github.com/hapijs/subtext/pull/37.
Closes #3352 
Closes #3354 
Closes #3355

Fix subtext shrinkwrap

---

API.md
lib/defaults.js

os.tmpdir was deprecated in Node 7.0.0. See https://nodejs.org/api/os.html#os_os_tmpdir and https://github.com/nodejs/node/pull/6739
fixes #3369

change deprecated os.tmpDir call to os.tmpdir

---

lib/transmit.js
test/transmit.js

Fix for #3378 Let me know when it's all clear and I'll squash.
Cheers,
Wes

Ensure Boom objects can be reused - Fix for issue #3378

---

lib/connection.js
test/connection.js

This is a possible fix for https://github.com/hapijs/discuss/issues/395, where longpoll HTTPS requests were getting cancelled *before* the timeout value passed to `server.stop()`.
**Fair warning**: I'm not very familiar with Hapi internals nor low-level Node HTTP & socket handling, so I don't have any idea if this fix is appropriate. Any and all suggestions—or a complete rewrite!—more than welcome! My real goal is simply to get this particular issue fixed in whatever manner is fastest. :-D 
`server.stop({timeout}, callback)` should wait for the provided timeout before forcibly closing any pending requests.
For HTTPS requests **only**, `server.stop` **immediately** forcibly closes pending requests, without waiting for either a response to the request or for the timeout.
It looks like …

Fix for hapijs/discuss#395.

---

lib/handler.js
lib/response.js
test/handler.js

This patch proposes a fix for #3242 ; 
The fix revolves around explicit domain bindings and execution of promise handler from the event loop (using process.nextTick) so that the error is not swallowed up by the promise itself (which was basically leading to a deadlock; the promise never fully resolved, and the callback is never called )
This is technically a bugfix, and I wasn't sure if I'm supposed to increase the patch version number, so I'll leave it up to you guys.

fix server not propagating errors on prehandler(promise) + handler error (#3242)

---

lib/handler.js
test/handler.js

I wrote a failing test witch match the description on #3399 and added a check to see if domain exists before binding. I also changed `domain = process.domain` to `domain = request.domain` to prevent the test domain from being used.
I'm sorry in advance if this fix is no good, I just recently started to studying the hapi internals

Attempt to fix #3399 where it crashes on route prerequisites when no domain is present

---

lib/protect.js

Closes https://github.com/hapijs/discuss/issues/433

remove extra closure

---

API.md

This can cause weird issues when you rewrite the url in plugins and then rewrite it again in example to the raw url.

Do not use raw request in api docs example

---

API.md
test/state.js

I don't know if this kind of PR is appreciated?  I saw the example of setting a cookie using an object in the [helpful tutorial docs](https://hapijs.com/tutorials/cookies?lang=en_US) and thought it would be worth while to have it in the hapi tests?

Add test for base64json cookie setting and parsing

---

API.md

From https://github.com/hapijs/discuss/issues/480.
Wording copied from the original docs in https://github.com/hapijs/hapi/commit/7cb9f0eca7d433d928b124fcd37b6211b0a0f250.

Update reply.takeover() docs to reflect implementation

---

API.md

Updated the code slightly to include `.code(error.output.statusCode)` at the end of the reply, because with that code the templates are rendered and a 200 status code is sent instead of something like 404 or 500.

Update Documentation for Code on onPreResponse

---

lib/reply.js
test/handler.js

Fix for https://github.com/hapijs/discuss/issues/445.
This ensures that any built-in request continuation methods are called using the correct domain. This is needed since promises lose the domain binding when eg. `reply()` is called inside a `.then()`.

Bind request continuation methods to current domain

---

lib/connection.js
lib/request.js
lib/route.js
test/payload.js

This patch enables clients that use the `expect: 100-continue` header to defer and possibly completely omit uploading data if the request fails before the "payload parsing" stage.
It can be further deferred, but this requires changes to subtext (see https://github.com/hapijs/subtext/issues/46).

Defer 100-continue signalling until payload parsing

---

test/payload.js

This fixes the observed flakiness in the test from #3472.
The reason it failed was that `Buffer.byteLength(new Buffer(10 * 1024 * 1024).toString())` returns a values that is `>= 10 * 1024 * 1024`. The exact value depends in the semi-random bytes allocated.
The fix avoids converting it to a string, thereby retaining the original size. Additionally I allocated a smaller buffer, since the large one was not needed.
/cc @Marsup

Fix flaky test from #3472

---

API.md
lib/plugin.js
lib/reply.js
lib/request.js
lib/server.js
test/plugin.js

Addresses enhancement request: https://github.com/hapijs/hapi/issues/3408

Adding server.inspect to list decorated framework interfaces

---

lib/request.js
test/request.js

This PR fixes this following issues in the `request.setUrl()` method:
* The passed url object is not cloned.
* Trailing slash stripping should be done after normalization (important if hapijs/call#29 is implemented).
* Always update pathname derived url properties when path is modified.
This should make for a safer and more consistent `request.setUrl()` experience.

Fix several request.url property issues on setUrl()

---

lib/connection.js

node versions >= 6 no longer destroy sockets by default when a clientError listener is attached, we have to do so ourselves

explicitly destroy sockets on clientError

---

npm-shrinkwrap.json
test/transmit.js

Node 8 changes the `stream.Readable` implementation a bit. Some of the tests expects the `.destroy()` method to be absent, which I fixed by always clearing it.
The more serious issue, is `server.inject()`, which can return incorrect headers. This is not a test issue, but rather a bug, which is fixed by updating to the latest `shot` release.
Closes #3510

Node 8 fixes

---

API.md
lib/handler.js
lib/promises.js
test/handler.js
test/promises.js

This small change allows an extra degree of protection for those who might be using promises in their handlers.
Developers who are using promises in their handlers will often write handlers which look like this:
```js
function handler(request, reply) {
doSomething
.then((interimResult) => {
return somethingElse(interimResult);
})
.then((result) => {
reply(result.whatever);
});
```
The challenge is that this opens up lots of opportunities for exceptions at different points to lead to uncaught promise rejections. For example:
```js
function handler(request, reply) {
doSomething
.then((interimResult) => {
throw new Error('whoops...');
})
.then((result) => {
reply(result.whatever);
});
```
will lead to a timeout of the request.
Rather than attempting some kind of large scale change which adds …

Provide cover for unhandled rejections

---

API.md

Some other clarifications to docs as well where validation options are passed and promise status from `server.inject()` calls.

Clarify documentation on validation function value and callback value

---

lib/reply.js
test/reply.js

After 16.2.0, it's not possible to decorate the reply object with something different to a function. This is due to the work originated on https://github.com/hapijs/hapi/pull/3448 where all reply methods are being bound to the request domain.
After that @hueniverse made a change to make sure that decorator methods are also bound to the domain, but it expects that any decoration added to the reply is also a function.
We were able to fix our issue by checking first that the decoration is in fact a function, and only bound it if that's the case.
I'm not sure if this is really a fix and if it's expected to be able to decorate the reply with something different to a function. I see that you always name the decoration as "method", but on the …

allow decoration of reply with non functions

---

API.md
lib/server.js
test/plugin.js

Consider wildcard filtering for debug options

---

API.md
lib/route.js
lib/schema.js
test/route.js

Hi All,
This PR adds a custom handler implementation to the route payload failAction, much like the route validate failAction. It addresses #3509.
I have also added tests for the three string failAction types, along with a test for the new functionality.
I'm consistently getting an error in one test locally that was present before I made these changes:
```
Failed tests:
757) transmission transmit() handles stream errors on the response after the response has been piped (inject):
Timed out (3000ms) - transmission transmit() handles stream errors on the response after the response has been piped (inject)
```
Just a head's up.
Thanks!

Add payload fail action custom handler

---

lib/transmit.js
test/transmit.js

res.statusMessage should assign before calling res.writeHead() explicitly. see https://nodejs.org/api/http.html#http_response_statusmessage

fix response.message(httpMessage)

---

API.md

The step to validate request headers is currently missing within the request lifecylce list (in `API.md`).
[Adri’s tweet](https://twitter.com/AdriVanHoudt_/status/899522763584655361) made me recognize it :)

add header validation step to request lifecycle in API.md

---

lib/validation.js
test/validation.js

I went with preserving the old response format, but this begs the question of whether it should send back keys as strings or array of strings now that it's possible. Thoughts ?

Support joi 11 paths arrays. Fixes #3581.

---

lib/response.js
test/response.js

When a hapi.js server is acting as a proxy or gateway, and a handler calls the reply/responder interface with a stream that is an IncomingMessage from an upstream, I believe the default behavior of the passThrough mode should be to not copy the connection header.
The semantics of the Connection header are that it represents per-hop connection options, and that a proxy or gateway MUST remove any connection options before forwarding a message (in this case a response to its client).  Basically connection options (usually keep-alive or close) should be negotiated between the server/client and between the server/upstream independent of each other.
The semantics of the Connection header are actually a little more complicated than that, because the header is supposed to be able to container …

exclude connection header in response passThrough

---

API.md
test/server.js

This commit adds a negative test around registering the same plugin multiple times with `once` defaulted to `false`. This test is to clarify the intent of the `once` flag by displaying the difference in behavior when it is not set.
API.md is also updated to reflect the behavior now that `connections` are removed.
NOTE: I actually think that `once` can be deprecated entirely, and the default `Error: Plugin ___ already registered` used for all subsequent registrations. Please let me know if you'd like me to do that instead and I will close this PR and open a new one to remove `once` entirely.

Add negative test on registering plugin twice without `once`

---

lib/config.js
test/validation.js

It fixes #3567
- Make `routeBase` schema allows `sample` props when `modify` is set to false
- Make `options.stripUnknown` assertion allows `false` value when `modify` is set to false

Loosen sample and modify peer validator in the routeBase schema

---

API.md

From `server.handler` to `server.decorate`

Remove deprecated server.handler reference in API.md

---

lib/toolkit.js
test/toolkit.js

This helps with debugging which function has the issue, which isn't always included in the stack trace

Include method name in error

---

API.md

I got this error when putting `state` under the server's `connections.routes`:
```
Error: Invalid server options {
"connections": {
"router": {
"isCaseSensitive": false,
"stripTrailingSlash": true
},
"routes": {
"state": {
"isHttpOnly" [1]: false
}
}
}
}
[1] "isHttpOnly" is not allowed
```
However it works when I put `state` under the server's `connections` (https://hapijs.com/api/16.6.2#new-serveroptions), like this:
```
{
connections: {
router: {
isCaseSensitive: false,
stripTrailingSlash: true
},
state: {
isHttpOnly: false
}
}
}
```
I'm confused since I thought `state` can be used as a route option (https://hapijs.com/api/16.6.2#route-options)

Correct server state configuration option

---

lib/compression.js
test/server.js

This implements #3701 and resolves https://github.com/hapijs/discuss/issues/589
Please let me know if I missed anything. And thanks a lot for the great framework ❤️

Prefer user added encoding over built-in

---

API.md

The documentation for both the `start` and `stop` server events states that the event handler uses the function signature `function()`, but the example code uses the function signature `function(route)`.

Fix signature in example for start/stop events

---

API.md

The `options` object was left behind causing a syntax error.

Minor server.method documentation fix

---

API.md

Fixed a typo in the documentation's example code

---

test/core.js
test/transmit.js

The tests are currently skipped on Windows, but there are no guarantees that `lsof` exists on the system executing the tests.
Refs: https://github.com/nodejs/citgm/pull/436

allow tests using lsof to pass on ENOENT

---

lib/core.js
test/payload.js
test/response.js
test/server.js
test/toolkit.js
test/transmit.js

Hi,
This is my first PR to hapi.js, after I posted in the discuss project ([Link](https://github.com/hapijs/discuss/issues/631)) 
This PR is related to the issue with using `new Buffer()`. As you probably know, `new Buffer()` has been deprecated due to security issues and replaced by `Buffer.from()`.
The changes:
- replaced all new Buffer(string) with Buffer.from(string)
- replaced all new Buffer(size) with Buffer.alloc(size)
I followed the "contributing guidelines" including tests.

Replace new Buffer()

---

lib/response.js
test/response.js

The `created` status code helper should also be valid at least for `PATCH` calls. 
BTW: Should this assertion even exist? I'd be in favor of getting rid of it and allow developers break the rules as they see fit.

Add PATCH to `created` status, better error msg

---

API.md

There looks to be a typo in:
> Contains the default authentication configuration **is** a default strategy was set via server.auth.default().
PR changes it to:
> Contains the default authentication configuration **if** a default strategy was set via server.auth.default().

Fixes typo on server.auth.settings.default description

---

API.md

The following PR is an update to `API.md` and addresses the following:
`Response` event example
- updates example that uses `request.id` to `request.info.id`
- updates link to `response-toolkit` in `failAction` configuration section
- update how to override response in `request.response`, removing reference to `repy(response)`

Documentation Update: `server.events` example in API.md

---

API.md
lib/server.js
test/request.js
test/server.js

Currently, the `property` argument of `server.decorate()` must be a string. This commit adds support for symbols as well, in order to provide unique, quasi-private decorations.

support symbol properties in server.decorate()

---

lib/core.js
lib/request.js
lib/server.js
test/request.js

Here I'm piggy-backing the discussion in #3795 and the initial work @cjihrig did to fix/test #3718.
This change prevents request decorations from being attached to the shared `Request` prototype. This was leading to decorations being leaked between servers in the same process.

do not attach request decorations to a shared prototype, alternative approach.

---

API.md

This PR fixes a typo related to payload validation on routes.

fix typo in route.options.validate.payload

---

test/core.js

This test attempts to clean up after itself, but just to be safe, remove the file before running the test.
Refs: https://github.com/nodejs/citgm/pull/436#issuecomment-413586574

remove unix domain socket before attempting to use it

---

API.md
lib/request.js
test/cors.js

Enclosed is a fix for #3813.
When an error occurs in `onRequest` hapi would throw because it expected `request.info.cors` to exist, but the route (and its CORS info) naturally hadn't been looked-up yet.  The bug was introduced in the fix for #3792, which made server CORS defaults apply to the special "notFound" route, which is the effective route during `onRequest`.
The fix here is to set `request.info.cors` prior to `onRequest` based upon the server's default CORS settings.  An alternative fix would be to compute `isOriginMatch` when attempting to set CORS headers specifically in the case of a special "notFound", rather than attempting to read it off of `request.info.cors`.

Ensure request.info.cors is set for special routes

---

lib/config.js
lib/request.js
test/request.js

I had a look into what it would take to update hapi to use the [WHATWG URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api) since `Url.parse()` [is being deprecated](https://github.com/nodejs/node/pull/22715), and node 8 already supports the replacement API.
As far as I can tell, the only directly affected api is the `request.url` property, and the `setUrl()` method.
PR details:
* All usage of old style **URL** objects, and `Url.parse()` has been replaced with the new **URL** API. There is no legacy support.
* Added a `route.queryParser` option to retain ability to customize the query parsing. The return value is validated so that `request.query` will always be an object.
* `request.url` property is no longer relative, since the **URL** constructor won't create relative URLs. …

Use WHATWG URL for request.url

---

SPONSORS.md

NZZ Storytelling is now called NZZ Visuals, see https://twitter.com/nzzvisuals/status/1042026666434994176.

Reflect change of team name

---

API.md

The documentation headers all use `route.options.something` but some examples were still using `config` instead of `options`. I updated the remaining ones.

Replace config with options to match newer Hapi naming

---

lib/auth.js
test/auth.js

**This PR includes a breaking change. If merged, this should be released with v18.**
Previously, the credentials from the tested authentication strategy were passed through. This PR changes the return value of `server.auth.test()`.
Changes:
- `server.auth.test()` now returns an object with the properties
- `credentials (required)
- `artifacts` (optional)
---
PS: If merged, I’ll send another PR to update the docs

Return credentials and artifacts from server.auth.test()

---

test/transmit.js

This break the test and shows the test doesn't actually work on node 10.
This points out something I bought up in https://github.com/hapijs/hapi/issues/3899
This test is also broken on v16 on node 10 for probably the same reason.

fix(transmit test): add missing await on team.work

---

API.md

Was reviewing the diff for the [v18.1.0](https://github.com/hapijs/hapi/compare/v18.0.1...v18.1.0) release and noticed this. Just wanted to quickly grab the fix there.

Fix typo in API.md attach -> attack

---

lib/response.js
lib/streams.js

Stream detection via `stream instanceof Stream` does not work correctly in browser contexts such as Chrome Apps or [WebExtensions in browsers exposing `chrome.sockets`](https://github.com/ipfs-shipyard/ipfs-companion/issues/664),  especially when different `stream` polyfils are used and mixed together.
This change replaces `instanceof Stream` checks with feature-detection of stream contract, enabling Hapi to be used in browserified form in Chrome Apps and other browser environments.
cc https://github.com/ipfs-shipyard/ipfs-companion/issues/716

Add support for Chrome Apps and WebExtensions

---

lib/core.js
lib/streams.js
test/request.js

It turns out that the trigger in #3969 does indeed contain a bug. Namely that a request, that is aborted during the request lifecycle, can cause a timeout, and log a 503 response even though nothing was ever sent down the wire.
Further investigation found that this was caused by the stream draining code in the default handler, which never completes if the stream is aborted. This in turn means that the `_lifecycle()` call in `request._execute()` never returns, and thus skips the call to `_reply()` that would clear the timeout timer.
The other part of the patch relates to the `clientError` handling. Here I found a case where a client can receive a `400 Bad Request` response, while the server logs it as a regular response.
This is because, contrary to the node docs, the `clientError` event …

Fix some corner case client errors

---

API.md

Added an extra "#" to both server.on and server.once for consistency on the hapi.dev self-generated api toc

Fix server.on and server.once api headings

---

lib/auth.js
test/auth.js

Currently request.auth is only populated on failed auth if the mode is set to 'try'
This will make that object always populated, regardless of auth mode.

fix(auth): properly populate request.auth on failed auth

---

lib/core.js
lib/handler.js
lib/request.js
lib/server.js
test/request.js

Hello,
This PR fixes a bug where Symbol decorations would not get added to request instances when `{ apply: true }` option was used. The issue was caused by iterating over decorations object using `for...in` which only iterates over enumerable properties (symbols are not enumerable)
Since Symbols are expected property names this PR fixes the issue above by also iterating over known symbol properties using `Object.getOwnPropertySymbols`.

Decorate requests with symbols with apply=true

---

lib/request.js
test/request.js

This commit adds a `toJSON()` method to the class used to create `request.info`. This ensures that `request.info` can be safely stringified in the presence of circular data structures.
Fixes: https://github.com/hapijs/hapi/issues/4019

support JSON.stringify() of request.info

---

API.md

I recently noticed some API reference examples were using `route.config` instead of `route.options` even though the documentation uses [route.options](https://hapi.dev/api/?v=19.1.1#route-options) to document them. 
Reading the hapi 17 [release notes](https://github.com/hapijs/hapi/issues/3658) looks like the former is to be deprecated in future versions, so went ahead and updated the usage examples.

[update-routes-config] Update API reference to use route.options

---

API.md

While trying to use `server.validator()` and struggling a bit while combining it with plugins, I learned just after reading the [hapi@19 release notes](https://github.com/hapijs/hapi/issues/4017) that when used inside a plugin, it only affects the current plugin's routes.
I am updating the documentation by adding a note similar to the one on [server.bind](https://hapi.dev/api/?v=19.1.1#-serverbindcontext) to clarify those details.

[server-validator-docs] Update server.validator() documentation

---

API.md

This should resolve a documentation layout issue on hapi.dev. It seems like all of the options displayed after `server.options.host` are displayed improperly in the sidebar, leading it to look like the options disappeared in v19.1.1:
I'm guessing the parser started parsing a new tree upon encountering the H3.
I have not tested the change, however it seems like this change 1) is very low risk and 2) is the formatting that seems most consistent with the rest of the docs, in addition to most likely fixing the issue.

v19.1.1 Server API options display issue on hapi.dev

---

lib/headers.js
test/headers.js

This commit prevents a null content-type header from being sent back.
Fixes: https://github.com/hapijs/hapi/issues/4133
Refs: https://github.com/hapijs/hapi/commit/ed0688c596d65ada38bea000ab6726c823a0abd9

headers: avoid sending null content-type

---

package.json

handlebars is only a devDependency, but update the version due to
a security advisory.
Refs: https://github.com/advisories/GHSA-q2c6-c6pm-g3gh

update handlebars dependency version

---

API.md

Someone reported on the Slack channel that we have broken Joi documentation link on the website. These links were picked up from the hapi API file.
Fixes https://github.com/hapijs/hapi.dev/issues/414

Update joi documentation links

---

lib/auth.js
test/auth.js

**How to reproduce?**
When a default scope is specified by the default strategy (`server.auth.default()`) and a route is configured with auth options (but not `access.scope`), the default scope is not taking effect and instead throws an error as described by #4083.
**Root cause**
Default strategy's scopes are [parsed](https://github.com/hapijs/hapi/blob/master/lib/auth.js#L419), changing the original value from an array (access.scope = []) to an object (access.scope = { ... }). When a route does not specify it's own scopes, the default strategy scopes are used, but at that point they are no longer an array.
**Fix**
This PR fixes the issue by ignoring `access.scope` if it has already been setup in default strategy

[default-scope] Accept default scope as a valid route scope

---

API.md

According to the release notes of 19.0.0 https://github.com/hapijs/hapi/issues/4017, the default `emptyStatusCode` is now `204` which is how it really works. The documentation here was out of date.

Fix default `emptyStatusCode`  in API.md

---

lib/server.js
lib/transmit.js
test/transmit.js

#4182 brings-up valid concerns about the status codes reported by `server.inject()` for response errors that occur after the original status code and headers have been written.  In the past these original status codes have been completely overwritten.  Now it should be accessible on `server.inject()`'s `response.raw.res.statusCode`, which may differ from `response.statusCode` when an error happened after the status code was written.  This work additionally fixes `response.statusMessage`, which was out of sync with `response.statusCode` in these cases.
For some history on status codes reported by `server.inject()` see also https://github.com/outmoded/discuss/issues/729 https://github.com/hapijs/hapi/issues/3878 https://github.com/hapijs/hapi/issues/3561

Preserve original response status on error after write, fix status message

---

README.md

This should make the list of current maintainers more discoverable.

doc: add TSC member list to README

---

test/common.js
test/core.js
test/request.js
test/transmit.js

There are a few issues to fix for failures in citgm:
1. Tests that rely on lsof on node v14.  @cjihrig previously made a fix for this in https://github.com/hapijs/hapi/pull/3744, but on node v14 the way to detect this error changed. https://github.com/nodejs/citgm/pull/436#issuecomment-754156977
2. Some flaky/failing tests on macos and AIX.  As far as I can tell the issue here is flakiness due to timing-dependent tests and slow IO in CI.  I attempted to make these tests less timing-dependent and to better cleanup after themselves, which allows them to be retryable.  I would love some review of these changes, as they are some of the more complex tests in the hapi test suite. https://github.com/nodejs/citgm/pull/436#issuecomment-751786801
CC @AdriVanHoudt I know in …

Fix tests for citgm

---

lib/request.js
lib/transmit.js
test/transmit.js

There's a fun story here!
In https://github.com/nodejs/citgm/pull/436 it was brought to our attention that node v15.7.0 caused a test to reliably fail in hapi's test suite.  I found that the test fails due to the relative timing of request `abort` versus response `close` timing: prior to node v15.7.0 the response would close in a later tick than the request would abort, and now these occur in the same tick.  This means that during hapi's transmission step, where it would typically still assume that the request or response would still have some events to emit (namely, a response `close`), that there would be no more event from `req` and `res`.  The first thing I did was adjust this test to remove the timing discrepancy across node versions, so that it always takes the most aggressive …

Allow for res to have already closed during transmission

---

lib/request.js
package.json

There was a regression in node v15.5.0 which broke hapi.  We learned that this was considered a bug in node v15, but that a comparable change would land in node v16.  As such, we now rely on res rather than req to handle premature `'close'` events.  This small alteration should be compatible with node v12+, and is not considered a breaking change.  This relies on a change within shot referenced below.
Refs: https://github.com/hapijs/hapi/issues/4208  https://github.com/hapijs/shot/pull/139 https://github.com/nodejs/node/pull/33035

Future-proof hapi for node v16, rely on res close rather than req

---

test/request.js

This fixes a test failure surfaced by citgm against node v16 nightly https://github.com/nodejs/citgm/issues/852.  In the past we have seen this test be [a bit flaky on OSX](https://github.com/hapijs/hapi/runs/2155975306)— hopefully this addresses that issue as well.
The issue is that the test relies on the relative timing of various node events.  Previously three requests were made to hapi, and during the first one the requests are aborted by the client.  For previous versions of node, the first two of those three requests were able to make it through before the server saw the client disconnect.  In node v16 the disconnect occurs nearly immediately, and only the first of the three requests were able to make it through.  To fix this, I ensure that the second and third requests experience …

Fix abort test timing to be consistent from node v12 through v16

---

API.md

Someone opened a PR on DefinitelyTyped repo regarding an undocumented behavior of `response.charset()` in the typings. It's also undocumented in the API documentation so I thought we ought to add it. Source: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52285#issuecomment-816824526

Mention response.charset() clear behavior

---

.github/workflows/ci-module.yml
package.json

We're using the approach outlined [here](https://github.com/hapijs/lab/pull/1004#issuecomment-824109034) to ensure `'*'` listed in CI pulls the latest version of node.  Also updating to lab 24.2.0 which supports node v16's new globals.
Refs: https://github.com/nodejs/citgm/issues/852 https://github.com/hapijs/lab/pull/1004

Update test suite to cover node v16

---

SPONSORS.md

The sponsor list list was out of date and out of sync with https://github.com/hapijs/.github/blob/master/SPONSORS.md, which is the official list appearing on the website.  I figured a reasonable compromise for now would be to list top sponsors here, which change less often, then link out to the extended list.

Update sponsors.md, link to the maintained list

---

test/request.js

There [was a change](https://github.com/nodejs/node/pull/38614) to the `ERR_INVALID_URL` constructor to stop reflecting the input in the error message that was landed in node 16.2.0, this adjusts our assertion so that both the new and old message will pass.
An alternative would be to start passing the `code` property from the error into the response, which I don't really love but one could certainly make a case for.

Fix request test to account for changes to ERR_INVALID_URL in node 16.2.0

---

lib/response.js
lib/toolkit.js
lib/transmit.js
test/response.js

This is in response to #4256.
I added asserts to verify the expected state so this kind of error are less likely to be introduced in future code. This also caught another error, where the `marshal()` method could sometimes be called _after_ `close()`.

Add response lifecycle tracking and checks

---

test/transmit.js

I fixed the test to be compatible with node 16, which allows the `req` to be closed while the connection itself is still active.
I also revised the stream, so we can really validate that the processing is stopped.
This is in response to https://github.com/hapijs/hapi/issues/4262#issuecomment-864614011.

Harden stream processing close test

---

lib/transmit.js
test/transmit.js

Addresses #4262.  On node v16 hapi would cut short any response that was transmitting while the request stream ended.  This is not especially common, partly because the request stream is often used prior to transmitting the response, and partly because this case does not apply when the request stream is not read at all i.e. for GET requests.
I believe this change is sound and backwards compatible because on node versions prior to v16, both req and res `'close'` events have identical meaning: the underlying connection shared by req and res has closed.  For this reason, there is no need to add listeners to both req and res on node <v16.
Starting with node v16 the `'close'` event for req no longer relates to the underlying connection, best documented at …

Fix req end during response transmission

---

API.md
lib/auth.js
lib/request.js
test/auth.js

Adds optional support to disable payload authentication when credentials are injected. Solves #4214

Add optional payload authentication skip on credentials injection

---

API.md
lib/auth.js
lib/server.js
test/auth.js

We were seeing some hard-to-explain behavior in #4218 as it relates to the realm of the `server` inside of auth schemes.  In short, each time `server` is cloned, _all_ servers were being mutated such that `server.auth.strategy` was bound to the server of the most recent clone.
Cloning is the process by which hapi creates independent realms for a. each plugin and b. each auth strategy.  When `server` is cloned, the clone's `realm.parent` is assigned to `server.realm`.  Due to the mutation of a shared interface during each clone, the `server.realm` within an auth strategy had a strange/unpredictable chain of ancestor realms.  This work tidies that up by no longer mutating the shared `auth` on each clone, instead creating a new public auth interface for each one.
Resolves #4218.

Fix handling of auth scheme/strategy realms

---

test/core.js
test/handler.js

Fix tests for node@16 error format change

---

.github/workflows/ci-module.yml
package.json
test/common.js
test/core.js
test/payload.js
test/request.js
test/server.js
test/transmit.js

While we will not officially support node v17 since it is not an LTS version of node, in practice we would like to test hapi against it and ensure everything will be in good shape when node v18 eventually arrives.
The hapi test suite was affected by the change in DNS ordering in https://github.com/nodejs/node/pull/39987, since default hapi servers would need to be connected to using `::1` over ipv6 rather than `127.0.0.1` over ipv4.  In the next major version of hapi we should consider how we might make our `address` default (currently `0.0.0.0`) more ipv6-aware.
We are also currently affected by a bug https://github.com/nodejs/node/issues/40528 slated to be resolved in node v17.1.0.  The one `skip()` in the test suite relates to this: we skip the test for now to avoid a hang caused by …

Fix tests for node v17

---

package.json

This is related to https://github.com/hapijs/teamwork/issues/32. @kanongil spotted a memory leak on https://github.com/hapijs/hapi/issues/4343#issuecomment-1072244342. The leak stems from `hapi`'s `server.ext()` method that leverages long standing Teamwork instances when no method are passed for an extension point. Since `teamwork` didn't clear its internal notes ref once the meeting was over, objects passed to `team.attend()` were never garbage collected and it also kept adding notes to an ended meeting.
The fix was provided in `@hapi/teamwork@5.1.1` thus the PR only updates `hapi` dependency.

Fix memory leaks from teamwork long standing notes

---

lib/toolkit.js

The functionality of switching the response from `prepare()`'s return value is removed.  As outlined in #4299, this was undocumented and not a very safe behavior.

Ignore return value from generateResponse() prepare method

---

API.md
lib/config.js
lib/security.js
test/headers.js

This adds support for configuring the `x-xss-protection` security header to `0`, and makes that the default in light of security issues that have been identified with XSS auditors/filters which are enabled by this header.  This is also OWASP's recommendation, and it's widely employed by sites such as Facebook, Google, and this one (GitHub!).
Resolves #4327

Change XSS header default to '0'

---

API.md
lib/config.js
lib/cors.js
test/cors.js

This work decouples the status code used for CORS preflight responses from the server's `emptyStatusCode`.  The CORS preflight response status code now defaults to `200` per conversation in #4165, and is configurable to `200` or `204` using `request.options.cors.preflightStatusCode`.
Resolves #4165

Change default CORS preflight status code w/ configuration

---

API.md
lib/validation.js
test/validation.js

Following from the conversation in #4040, I've added the default validation error to `err.data.defaultError` where `err` is the detailed error passed to `failAction()` for input validation.  Since the common use-case seems to be logging detailed validation errors without modifying the error response, I considered logging the detailed error by default.  But I determined that it contained user input which could be sensitive: I believe users should opt-in to this behavior with a custom `failAction()` rather than it become the default `'log'` behavior.  Here's how that would look with this update:
```js
server.route({
method: 'get',
path: '/',
handler: () => 'ok',
options: {
validate: {
query: {
a: Joi.string().min(2)
},
failAction: function (request, h, err) {
request.log(['validation', …
```

Make default error available in validation failAction

---

lib/response.js
lib/streams.js
test/response.js
test/transmit.js

Dropping support for old/non-standard response streams.  If you want to use one of these, you can try repairing it into a `Stream.Readable` by piping it through a `Stream.PassThrough`.  I ended-up keeping the old stream duck-typing logic around for the purpose of helping users catch any issues when moving from v20 to v21, rather than treating legacy streams as an object response.
Resolves #4293

Enforce that response streams are always Stream.Readable

---

.github/workflows/ci-module.yml
lib/auth.js
lib/core.js
lib/handler.js
lib/headers.js
lib/methods.js
lib/request.js
lib/response.js
lib/route.js
lib/security.js
lib/server.js
lib/toolkit.js
lib/transmit.js
lib/validation.js
package.json
test/core.js

Dropping node v12 support.  There's a good discussion in #4279 that outlines other steps we may want to take as we end support for node v12.  Here's my approach here:
- I adopted nullish coalescing and optional chaining.
- Recognizing that it might break code that relies on the old behavior, I did adopt `??` in the place of `||` when evaluating non-boolean expressions.  I am open to other thoughts, but I am of the mind that it usually gives a better, more precise behavior than `||`.  In some cases I kept `||` when I thought it made sense, e.g to fall through empty header values of `''`.
- I did not address the usage of private methods since hapi treats private methods as private to hapi and not just the class in question.  One great example is `request._log()` which is called all over the …

Drop node v12 support

---

API.md
lib/core.js
lib/request.js
package.json
test/common.js
test/core.js
test/payload.js
test/request.js
test/server.js
test/transmit.js

This changes hapi's default host of `0.0.0.0` to use node's IPv6-friendly default host of `::` or `0.0.0.0`, depending on whether the machine supports IPv6.
Under node v18 the drawbacks of the current default are emphasized, since DNS resolution in node has changed (https://github.com/nodejs/node/pull/39987) allowing `localhost` to resolve to the IPv6 address `::1`— since `0.0.0.0` was pinned to IPv4, a request to `localhost` from node would not be able to connect to a default hapi server.

Change default host to be IPv6-friendly

---

lib/config.js
lib/core.js
lib/server.js
package.json
test/core.js
test/request.js
test/server.js

Historically hapi has disallowed matching of prerelease versions when validating plugin `requirements`.  This has caused some issues, e.g. when node's CITGM runs hapi's test suite on upcoming versions of node (https://github.com/hapijs/somever/issues/18), or when testing plugins against the beta of hapi v21 (https://github.com/hapijs/inert/pull/164#discussion_r907095052).  In https://github.com/hapijs/somever/issues/18 we resolved to change this behavior within hapi. This PR addresses the issue, following from adding the feature to somever in https://github.com/hapijs/somever/pull/22.
I also updated the tests so that we don't trigger errors in the updated version of llhttp in node v18.5.0 ([ref](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-07-07-version-185 …

Allow matching prereleases when validating plugin version requirements

---

API.md
test/core.js

The `load.maxEventLoopUtilization` option was added in https://github.com/hapijs/heavy/pull/48, which was released as part of `@hapi/hapi` 21.x

Add documentation for server.options.load.maxEventLoopUtilization

---

API.md
lib/index.d.ts
package.json
test/types/index.ts

This adds the DT type definition AS-IS without any changes as well as creates a basic type tests setup. After spending a day trying to migrate the DT tests it was clear that they tests were too broken to reuse. The plan is to add more tests as we improve the types.

Move TypeScript definition from DT (as-is)

---

test/core.js
test/payload.js
test/request.js
test/transmit.js

One test depends on the specific behavior of `.abort()`, so I haven't changed it:
https://github.com/hapijs/hapi/blob/9c17cc0dc99570939a449b623fbd58aca3ecac92/test/response.js#L1213

Replace deprecated `.abort()` with `.destroy()`

---

lib/index.d.ts

* Fix `table` type definition.  See https://github.com/hapijs/call/blob/f4adca38ae29852fa5f990b13a0abbc36a53b924/lib/index.js#L325 and https://github.com/hapijs/hapi/blob/9c17cc0dc99570939a449b623fbd58aca3ecac92/test/core.js#L1489
* More updates to type definitions. These were found by checking WebStorm's list of type mismatches.  Most of them involve updating the type definitions to match API.md or to match the tests' usage.

Updates to TypeScript definitions

---

lib/index.d.ts

Hi team, 
#4352 has changed the way xss behaves but the types were not updated yet.

update types for xss

---

lib/types/request.d.ts

I am one of the previous maintainers of `@types/hapi__hapi` - after migrating away from it I noticed that a lot of properties inside the response were unavailable, and it seems to come down to the `ResponseObject` from `shot` being used instead of the actual `ResponseObject` from `hapi`.
As an example, this used to work, but doesn't with the current types:
```ts
server.ext('onPreResponse', (request: Request, h: ResponseToolkit): Lifecycle.ReturnValue => {
const { response } = request;
if (!response || response instanceof Error) {
return h.continue;
}
response.events.on('peek', chunk => {
console.dir(chunk);
});
return h.continue;
});
``` 
Maybe it would also be good to migrate over all of the tests from DefinitelyTyped? I can try to attempt that if no-one else does, but I am very limited …

Correct the ResponseObject type

---

API.md
lib/types/route.d.ts

Fixes valid values of 'xss' security option in TS types and in the documentation. 
Context: The change https://github.com/hapijs/hapi/pull/4352 introduces string values `'enabled'` and `'disabled'` for the `xss` property. However, it adds `'enable'` and `'disable'` (mind the missing `d`) to the API documentation. Then, this change https://github.com/hapijs/hapi/pull/4401 adds those wrong values from the documentation to the Typescript types. Now if you use `xss: 'enable'` on a TS project, the code compiles but on runtime Hapi rightfully complains: `"routes.security.xss" must be one of [enabled, disabled, false]`. If you set it to `enabled` though the code no longer compiles due to the TS type declaration. This change fixes that and aligns the types with the values used at runtime.

Fix valid values of 'xss' property in types and documentation

---

README.md

I have not had the time to contribute as much as I would like and no longer use Node in my day job, so it's probably best to remove myself.

remove cjihrig from TSC

---

.labrc.js
lib/core.js
lib/transmit.js
test/core.js
test/payload.js
test/request.js
test/route.js
test/transmit.js

This fixes the test suite for node v18, v20 and v21 on my mac.

Node 20 fixes

---

lib/toolkit.js

Returning promise without await causes Node.js to lose stacktrace context making hapijs app harder to debug

failAction loses stacktrace context

---

lib/types/utils.d.ts

Support for pre handlers whose type definition is only a subset of the actual route type definition.
When trying to reuse pre handlers in a typescript environment like the following
```typescript
const doSomething: Lifecycle.Method<any> = async ({ params }) => {
console.log(params.preParam);
};
server.route<{ Params: { param: string, preParam: number } }>({
method: 'GET',
path: '/route',
handler: async ({ params }) => console.log(params.param),
options: {
pre: [ doSomething ]
}
});
server.route<{ Params: { otherParam: string, preParam: number } }>({
method: 'GET',
path: '/route',
handler: async ({ params }) => console.log(params.otherParam),
options: {
pre: [ doSomething ]
}
});
```
The type definition of the pre handler does not have any possible valid value, hence needing to drop type …

fix(types): enhance reusability of pres

---

lib/types/route.d.ts
lib/types/server/encoders.d.ts
lib/types/server/index.d.ts
lib/types/server/server.d.ts

This PR improves the typings of the route and payload `compression` options, by explicitly listing the available encoders (`gzip` & `deflate`) and types all the options.
Additionally, it allows users to register types for custom encoders/decoders with its own custom options. Eg.
```ts
import { createBrotliCompress } from 'zlib';
declare module '@hapi/hapi' {
interface ContentEncoders {
br: typeof createBrotliCompress;
}
}
```
This will add and type a `br` encoder to `servers.encoders()`, and add it to the list of `compression` options with the expected typings.
Note that I deleted the nonsensical `RouteCompressionEncoderSettings` and `PayloadCompressionDecoderSettings` type exports (the settings have always been specific to each entry).

Make content encoder and options explicitly typed and extensible

---

.labrc.js

Node 18.19.0 no longer allows requests after close().

Fix CI on node 18.19.0+

---

lib/types/index.d.ts
lib/types/request.d.ts
lib/types/route.d.ts
lib/types/utils.d.ts

This fixes several issues with the current http method verb handling:
1. Explicit list *all possible* verbs for `request.route()` definitions, including `'*'`.
2. Disallow using `string` for `request.route()` method, since it made it prone to misspellings.
3. Only allow lowercased verbs including `'head'` for `request.method` (fixes #4492).
4. Only allow lowercased verbs and `'*'` values for `request.route.method`.
5. Allow `'HEAD'` and lowercased verbs for `request.setMethod()`.
As with any changes to the typings, this can break the type checks in projects that use hapi. I expect this will mostly just work, but there can be esoteric cases where some work will be required to fix it after updating.

Cleanup http methods typings

---

lib/types/server/server.d.ts
test/types/index.ts

#4493 caused a compilation failure when reinjecting `request.method` into `server.match` on my project.

types: allow server.match to receive lowercased methods

---

lib/types/route.d.ts
lib/types/server/methods.d.ts
package.json
test/types/index.ts

🎟️ Fixes #4505 #4501
Additionally adds missing method cache typings to select cache name and segment name

fix: 🐛 route payload options missing types

---

test/handler.js
test/request.js

This adds a test for the `error.stack` property to illustrate a node v22 regression.
This should be able to be fixed with https://github.com/hapijs/hoek/pull/390.
Again, feel free to backport my old PR to fix this, but personally I would prefer to declare that Hapi v21 and any modules that use `Hoek.clone()` on potential errors (at least Hoek, Boom, and Podium) does not support node 21+.

Test that logged simple handler errors has a stack

---

API.md

Update event tags in documentation

---

lib/server.js
lib/types/plugin.d.ts
lib/types/server/server.d.ts
test/server.js
test/types/index.ts

- Types match the validation a bit more. 
- Type errors when attempting to decorate a builtin.
- No `any` when decorating a non-method
- Can never extend a handler method
- Can never extend or apply a non-method
Continued from https://github.com/hapijs/hapi/pull/4525

fix: 🐛 typings around server.decorate

---

lib/types/server/methods.d.ts
lib/types/server/server.d.ts
test/types/index.ts

~also fix pre typing issue~ would be fixed by https://github.com/hapijs/hapi/pull/4489 . Change removed.

fix: 🐛 allow typed server methods access cache methods

---

lib/types/plugin.d.ts

Closes https://github.com/hapijs/hapi/issues/4537

fix: 🐛 less ambigious plugin types
